/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    leads: Lead;
    companies: Company;
    deals: Deal;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    deals: DealsSelect<false> | DealsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published' | 'archived';
  client?: string | null;
  year?: number | null;
  categories?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  summary?: string | null;
  cover?: (number | null) | Media;
  accent?: string | null;
  pageTheme?: ('dark' | 'light') | null;
  blocks: (
    | {
        eyebrow?: string | null;
        title: string;
        dek?: string | null;
        media: number | Media;
        layout?: ('editorial' | 'media-first' | 'fullscreen') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'caseHero';
      }
    | {
        kicker?: string | null;
        text: string;
        size?: ('m' | 'l' | 'xl' | 'display') | null;
        align?: ('left' | 'center' | 'right') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'manifesto';
      }
    | {
        media: number | Media;
        caption?: string | null;
        height?: ('auto' | '70vh' | 'screen' | '120vh') | null;
        fit?: ('cover' | 'contain') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'fullBleedMedia';
      }
    | {
        left: number | Media;
        right: number | Media;
        ratio?: ('1-1' | '1-2' | '2-1') | null;
        gap?: ('none' | 'xs' | 's' | 'm') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'splitMedia';
      }
    | {
        items?:
          | {
              media: number | Media;
              caption?: string | null;
              span?: ('1' | '2') | null;
              id?: string | null;
            }[]
          | null;
        layout?: ('editorial' | 'grid' | 'rail' | 'staggered') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaMosaic';
      }
    | {
        chapter?: string | null;
        title: string;
        body: string;
        frames?:
          | {
              media: number | Media;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        pin?: ('copy' | 'media') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'stickyStory';
      }
    | {
        items?:
          | {
              value: string;
              label: string;
              note?: string | null;
              id?: string | null;
            }[]
          | null;
        style?: ('rail' | 'cards' | 'oversized') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'metrics';
      }
    | {
        before: number | Media;
        after: number | Media;
        beforeLabel?: string | null;
        afterLabel?: string | null;
        mode?: ('drag' | 'toggle' | 'split') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'beforeAfter';
      }
    | {
        text: string;
        author?: string | null;
        role?: string | null;
        size?: ('l' | 'xl' | 'display') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quote';
      }
    | {
        title?: string | null;
        steps?:
          | {
              number?: string | null;
              title: string;
              body?: string | null;
              media?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        mode?: ('timeline' | 'accordion' | 'sticky') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'process';
      }
    | {
        items?:
          | {
              media: number | Media;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        mode?: ('drag' | 'cursor' | 'stack' | 'filmstrip') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'gallery';
      }
    | {
        media: number | Media;
        device?: ('none' | 'browser' | 'phone' | 'screen' | 'print') | null;
        caption?: string | null;
        float?: boolean | null;
        theme?: ('dark' | 'light' | 'media') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'deviceShowcase';
      }
    | {
        title?: string | null;
        items?:
          | {
              role: string;
              name: string;
              id?: string | null;
            }[]
          | null;
        theme?: ('dark' | 'light' | 'media') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'credits';
      }
    | {
        project: number | Project;
        label?: string | null;
        theme?: ('dark' | 'light' | 'media') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'nextProject';
      }
  )[];
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email?: string | null;
  phone?: string | null;
  companyName?: string | null;
  company?: (number | null) | Company;
  source?: ('site' | 'referral' | 'outbound' | 'event' | 'other') | null;
  service?: ('presentation' | 'strategy' | 'branding' | 'web' | 'conference' | 'other') | null;
  budget?: number | null;
  status: 'new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost';
  owner?: (number | null) | User;
  nextActionAt?: string | null;
  notes?: string | null;
  relatedProject?: (number | null) | Project;
  utm?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
    content?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  name: string;
  domain?: string | null;
  industry?: string | null;
  owner?: (number | null) | User;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals".
 */
export interface Deal {
  id: number;
  title: string;
  company: number | Company;
  lead?: (number | null) | Lead;
  project?: (number | null) | Project;
  stage: 'discovery' | 'brief' | 'estimate' | 'proposal' | 'negotiation' | 'won' | 'lost';
  value?: number | null;
  currency?: ('RUB' | 'USD' | 'EUR' | 'AED') | null;
  owner?: (number | null) | User;
  nextActionAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'deals';
        value: number | Deal;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  client?: T;
  year?: T;
  categories?:
    | T
    | {
        label?: T;
        id?: T;
      };
  summary?: T;
  cover?: T;
  accent?: T;
  pageTheme?: T;
  blocks?:
    | T
    | {
        caseHero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              dek?: T;
              media?: T;
              layout?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        manifesto?:
          | T
          | {
              kicker?: T;
              text?: T;
              size?: T;
              align?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        fullBleedMedia?:
          | T
          | {
              media?: T;
              caption?: T;
              height?: T;
              fit?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        splitMedia?:
          | T
          | {
              left?: T;
              right?: T;
              ratio?: T;
              gap?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        mediaMosaic?:
          | T
          | {
              items?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    span?: T;
                    id?: T;
                  };
              layout?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        stickyStory?:
          | T
          | {
              chapter?: T;
              title?: T;
              body?: T;
              frames?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    id?: T;
                  };
              pin?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        metrics?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    note?: T;
                    id?: T;
                  };
              style?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        beforeAfter?:
          | T
          | {
              before?: T;
              after?: T;
              beforeLabel?: T;
              afterLabel?: T;
              mode?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              author?: T;
              role?: T;
              size?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        process?:
          | T
          | {
              title?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    media?: T;
                    id?: T;
                  };
              mode?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              items?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    id?: T;
                  };
              mode?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        deviceShowcase?:
          | T
          | {
              media?: T;
              device?: T;
              caption?: T;
              float?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        credits?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    role?: T;
                    name?: T;
                    id?: T;
                  };
              theme?: T;
              id?: T;
              blockName?: T;
            };
        nextProject?:
          | T
          | {
              project?: T;
              label?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
      };
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  companyName?: T;
  company?: T;
  source?: T;
  service?: T;
  budget?: T;
  status?: T;
  owner?: T;
  nextActionAt?: T;
  notes?: T;
  relatedProject?: T;
  utm?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
        content?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  domain?: T;
  industry?: T;
  owner?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals_select".
 */
export interface DealsSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  lead?: T;
  project?: T;
  stage?: T;
  value?: T;
  currency?: T;
  owner?: T;
  nextActionAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}