/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    articles: Article;
    'case-templates': CaseTemplate;
    media: Media;
    leads: Lead;
    companies: Company;
    deals: Deal;
    activities: Activity;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'case-templates': CaseTemplatesSelect<false> | CaseTemplatesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    deals: DealsSelect<false> | DealsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    overview: OverviewWidget;
    'quick-actions': QuickActionsWidget;
    'recent-projects': RecentProjectsWidget;
    'review-queue': ReviewQueueWidget;
    pipeline: PipelineWidget;
    'lead-inbox': LeadInboxWidget;
    activities: ActivitiesWidget;
    'block-library': BlockLibraryWidget;
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Кейсы BAEV собираются как последовательность режиссируемых блоков.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  lastEditedBy?: string | null;
  workflowStatus?: ('draft' | 'review' | 'ready' | 'paused') | null;
  owner?: (number | null) | User;
  deadline?: string | null;
  title: string;
  kind: 'project';
  /**
   * Создаётся из названия автоматически, можно изменить вручную.
   */
  slug: string;
  featured?: boolean | null;
  portfolioOrder?: number | null;
  role?: string | null;
  audience?: string | null;
  client?: string | null;
  year?: number | null;
  categories?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 2–4 предложения: контекст и задача. Используется в Hero и карточках.
   */
  summary?: string | null;
  cover?: (number | null) | Media;
  ogImage?: (number | null) | Media;
  /**
   * Единый фон всех блоков. Пустое значение сохраняет оформление блоков.
   */
  pageBackground?: string | null;
  /**
   * От 0 до 80. Пустое значение сохраняет исходное оформление.
   */
  mediaRadius?: number | null;
  accent?: string | null;
  pageTheme?: ('dark' | 'light') | null;
  bodyMode?: ('blocks' | 'embed') | null;
  embedURL?: string | null;
  embedHeight?: number | null;
  embedMobileHeight?: number | null;
  embedAutoHeight?: boolean | null;
  /**
   * Добавляйте сцены, меняйте порядок drag-and-drop. У каждого блока есть несколько режимов.
   */
  blocks: (
    | {
        eyebrow?: string | null;
        title: string;
        dek?: string | null;
        media: number | Media;
        layout?: ('editorial' | 'media-first' | 'fullscreen') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'caseHero';
      }
    | {
        kicker?: string | null;
        text: string;
        size?: ('m' | 'l' | 'xl' | 'display') | null;
        align?: ('left' | 'center' | 'right') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'manifesto';
      }
    | {
        media: number | Media;
        caption?: string | null;
        height?: ('auto' | '70vh' | 'screen' | '120vh') | null;
        fit?: ('cover' | 'contain') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'fullBleedMedia';
      }
    | {
        left: number | Media;
        right: number | Media;
        ratio?: ('1-1' | '1-2' | '2-1') | null;
        gap?: ('none' | 'xs' | 's' | 'm') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'splitMedia';
      }
    | {
        items?:
          | {
              media: number | Media;
              caption?: string | null;
              span?: ('1' | '2') | null;
              id?: string | null;
            }[]
          | null;
        layout?: ('editorial' | 'grid' | 'rail' | 'staggered') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaMosaic';
      }
    | {
        chapter?: string | null;
        title: string;
        body: string;
        frames?:
          | {
              media: number | Media;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        pin?: ('copy' | 'media') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'stickyStory';
      }
    | {
        items?:
          | {
              value: string;
              label: string;
              note?: string | null;
              id?: string | null;
            }[]
          | null;
        style?: ('rail' | 'cards' | 'oversized') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'metrics';
      }
    | {
        before: number | Media;
        after: number | Media;
        beforeLabel?: string | null;
        afterLabel?: string | null;
        mode?: ('drag' | 'toggle' | 'split') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'beforeAfter';
      }
    | {
        text: string;
        author?: string | null;
        role?: string | null;
        size?: ('l' | 'xl' | 'display') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quote';
      }
    | {
        title?: string | null;
        steps?:
          | {
              number?: string | null;
              title: string;
              body?: string | null;
              media?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        mode?: ('timeline' | 'accordion' | 'sticky') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'process';
      }
    | {
        items?:
          | {
              media: number | Media;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        mode?: ('drag' | 'cursor' | 'stack' | 'filmstrip') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'gallery';
      }
    | {
        media: number | Media;
        device?: ('none' | 'browser' | 'phone' | 'screen' | 'print') | null;
        caption?: string | null;
        float?: boolean | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'deviceShowcase';
      }
    | {
        title?: string | null;
        items?:
          | {
              role: string;
              name: string;
              id?: string | null;
            }[]
          | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'credits';
      }
    | {
        project: number | Project;
        label?: string | null;
        mode?: ('cover' | 'minimal') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'nextProject';
      }
    | {
        title?: string | null;
        scenes?:
          | {
              media: number | Media;
              title?: string | null;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        mode?: ('snap' | 'scrub') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'horizontalStory';
      }
    | {
        layers?:
          | {
              media: number | Media;
              x?: number | null;
              y?: number | null;
              width?: number | null;
              depth?: number | null;
              id?: string | null;
            }[]
          | null;
        mode?: ('stack' | 'parallax' | 'float') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'layeredMedia';
      }
    | {
        kicker?: string | null;
        text: string;
        mode?: ('center' | 'edge' | 'marquee') | null;
        accentWord?: string | null;
        align?: ('left' | 'center' | 'right') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'typographyTakeover';
      }
    | {
        video: number | Media;
        poster?: (number | null) | Media;
        title?: string | null;
        caption?: string | null;
        mode?: ('inline' | 'full' | 'sticky') | null;
        autoplay?: boolean | null;
        loop?: boolean | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'videoChapter';
      }
    | {
        title?: string | null;
        items?:
          | {
              title: string;
              value?: string | null;
              body?: string | null;
              id?: string | null;
            }[]
          | null;
        mode?: ('columns' | 'table' | 'cards') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'comparison';
      }
    | {
        items?:
          | {
              media: number | Media;
              label?: string | null;
              id?: string | null;
            }[]
          | null;
        mode?: ('fan' | 'stack' | 'spread') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'artifactStack';
      }
    | {
        eyebrow?: string | null;
        title: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        media: number | Media;
        layout?: ('text-left' | 'text-right' | 'balanced') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'textMedia';
      }
    | {
        title: string;
        body?: string | null;
        buttonLabel?: string | null;
        buttonURL?: string | null;
        media?: (number | null) | Media;
        mode?: ('minimal' | 'statement' | 'media') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        width?: ('full' | 'wide' | 'reading') | null;
        align?: ('left' | 'center' | 'right') | null;
        spacing?: ('none' | 'small' | 'medium' | 'large') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'editorialText';
      }
    | {
        media: number | Media;
        caption?: string | null;
        width?: ('full' | 'wide' | 'reading') | null;
        aspect?: ('auto' | 'landscape' | 'classic' | 'square' | 'portrait') | null;
        align?: ('left' | 'center' | 'right') | null;
        spacing?: ('none' | 'small' | 'medium' | 'large') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaFrame';
      }
    | {
        items: {
          media: number | Media;
          caption?: string | null;
          id?: string | null;
        }[];
        columns?: ('2' | '3' | '4') | null;
        gap?: number | null;
        width?: ('full' | 'wide' | 'reading') | null;
        aspect?: ('auto' | 'landscape' | 'classic' | 'square' | 'portrait') | null;
        spacing?: ('none' | 'small' | 'medium' | 'large') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaGrid';
      }
    | {
        items: {
          title?: string | null;
          body: string;
          id?: string | null;
        }[];
        width?: ('full' | 'wide' | 'reading') | null;
        spacing?: ('none' | 'small' | 'medium' | 'large') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'textColumns';
      }
    | {
        items: {
          label: string;
          value: string;
          id?: string | null;
        }[];
        width?: ('full' | 'wide' | 'reading') | null;
        spacing?: ('none' | 'small' | 'medium' | 'large') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'projectFacts';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        line?: boolean | null;
        height?: number | null;
        width?: ('full' | 'wide' | 'reading') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'sectionBreak';
      }
  )[];
  seoTitle?: string | null;
  seoDescription?: string | null;
  canonicalURL?: string | null;
  noIndex?: boolean | null;
  internalNotes?: string | null;
  /**
   * Внутренняя ссылка, на публичный сайт не выводится.
   */
  sourceURL?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor' | 'sales';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  sourceProtected?: boolean | null;
  /**
   * Коротко опишите изображение — используется для accessibility и SEO.
   */
  alt: string;
  kind?: ('project' | 'site' | 'cover' | 'brand' | 'motion') | null;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xl?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  lastEditedBy?: string | null;
  title: string;
  slug: string;
  author?: string | null;
  publishedAt?: string | null;
  summary?: string | null;
  cover?: (number | null) | Media;
  categories?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  blocks: (
    | {
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        title?: string | null;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        width?: ('reading' | 'wide') | null;
        theme?: ('light' | 'dark') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'articleText';
      }
    | {
        media: number | Media;
        caption?: string | null;
        height?: ('auto' | '70vh' | 'screen' | '120vh') | null;
        fit?: ('cover' | 'contain') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'fullBleedMedia';
      }
    | {
        left: number | Media;
        right: number | Media;
        ratio?: ('1-1' | '1-2' | '2-1') | null;
        gap?: ('none' | 'xs' | 's' | 'm') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'splitMedia';
      }
    | {
        items?:
          | {
              media: number | Media;
              caption?: string | null;
              span?: ('1' | '2') | null;
              id?: string | null;
            }[]
          | null;
        layout?: ('editorial' | 'grid' | 'rail' | 'staggered') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaMosaic';
      }
    | {
        items?:
          | {
              value: string;
              label: string;
              note?: string | null;
              id?: string | null;
            }[]
          | null;
        style?: ('rail' | 'cards' | 'oversized') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'metrics';
      }
    | {
        text: string;
        author?: string | null;
        role?: string | null;
        size?: ('l' | 'xl' | 'display') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quote';
      }
    | {
        title?: string | null;
        steps?:
          | {
              number?: string | null;
              title: string;
              body?: string | null;
              media?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        mode?: ('timeline' | 'accordion' | 'sticky') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'process';
      }
    | {
        items?:
          | {
              media: number | Media;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        mode?: ('drag' | 'cursor' | 'stack' | 'filmstrip') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'gallery';
      }
    | {
        video: number | Media;
        poster?: (number | null) | Media;
        title?: string | null;
        caption?: string | null;
        mode?: ('inline' | 'full' | 'sticky') | null;
        autoplay?: boolean | null;
        loop?: boolean | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'videoChapter';
      }
    | {
        eyebrow?: string | null;
        title: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        media: number | Media;
        layout?: ('text-left' | 'text-right' | 'balanced') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'textMedia';
      }
    | {
        title: string;
        body?: string | null;
        buttonLabel?: string | null;
        buttonURL?: string | null;
        media?: (number | null) | Media;
        mode?: ('minimal' | 'statement' | 'media') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
  )[];
  pageTheme?: ('light' | 'dark') | null;
  /**
   * Единый фон всех блоков. Пустое значение сохраняет оформление блоков.
   */
  pageBackground?: string | null;
  /**
   * От 0 до 80. Пустое значение сохраняет исходное оформление.
   */
  mediaRadius?: number | null;
  featured?: boolean | null;
  workflowStatus?: ('draft' | 'review' | 'ready' | 'paused') | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  ogImage?: (number | null) | Media;
  canonicalURL?: string | null;
  noIndex?: boolean | null;
  owner?: (number | null) | User;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Системные стартовые композиции для мастера создания кейса.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-templates".
 */
export interface CaseTemplate {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  pageTheme?: ('dark' | 'light') | null;
  accent?: string | null;
  /**
   * Этот порядок и содержимое копируются в новый кейс.
   */
  blocks: (
    | {
        eyebrow?: string | null;
        title: string;
        dek?: string | null;
        media: number | Media;
        layout?: ('editorial' | 'media-first' | 'fullscreen') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'caseHero';
      }
    | {
        kicker?: string | null;
        text: string;
        size?: ('m' | 'l' | 'xl' | 'display') | null;
        align?: ('left' | 'center' | 'right') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'manifesto';
      }
    | {
        media: number | Media;
        caption?: string | null;
        height?: ('auto' | '70vh' | 'screen' | '120vh') | null;
        fit?: ('cover' | 'contain') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'fullBleedMedia';
      }
    | {
        left: number | Media;
        right: number | Media;
        ratio?: ('1-1' | '1-2' | '2-1') | null;
        gap?: ('none' | 'xs' | 's' | 'm') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'splitMedia';
      }
    | {
        items?:
          | {
              media: number | Media;
              caption?: string | null;
              span?: ('1' | '2') | null;
              id?: string | null;
            }[]
          | null;
        layout?: ('editorial' | 'grid' | 'rail' | 'staggered') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaMosaic';
      }
    | {
        chapter?: string | null;
        title: string;
        body: string;
        frames?:
          | {
              media: number | Media;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        pin?: ('copy' | 'media') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'stickyStory';
      }
    | {
        items?:
          | {
              value: string;
              label: string;
              note?: string | null;
              id?: string | null;
            }[]
          | null;
        style?: ('rail' | 'cards' | 'oversized') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'metrics';
      }
    | {
        before: number | Media;
        after: number | Media;
        beforeLabel?: string | null;
        afterLabel?: string | null;
        mode?: ('drag' | 'toggle' | 'split') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'beforeAfter';
      }
    | {
        text: string;
        author?: string | null;
        role?: string | null;
        size?: ('l' | 'xl' | 'display') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quote';
      }
    | {
        title?: string | null;
        steps?:
          | {
              number?: string | null;
              title: string;
              body?: string | null;
              media?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        mode?: ('timeline' | 'accordion' | 'sticky') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'process';
      }
    | {
        items?:
          | {
              media: number | Media;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        mode?: ('drag' | 'cursor' | 'stack' | 'filmstrip') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'gallery';
      }
    | {
        media: number | Media;
        device?: ('none' | 'browser' | 'phone' | 'screen' | 'print') | null;
        caption?: string | null;
        float?: boolean | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'deviceShowcase';
      }
    | {
        title?: string | null;
        items?:
          | {
              role: string;
              name: string;
              id?: string | null;
            }[]
          | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'credits';
      }
    | {
        project: number | Project;
        label?: string | null;
        mode?: ('cover' | 'minimal') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'nextProject';
      }
    | {
        title?: string | null;
        scenes?:
          | {
              media: number | Media;
              title?: string | null;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        mode?: ('snap' | 'scrub') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'horizontalStory';
      }
    | {
        layers?:
          | {
              media: number | Media;
              x?: number | null;
              y?: number | null;
              width?: number | null;
              depth?: number | null;
              id?: string | null;
            }[]
          | null;
        mode?: ('stack' | 'parallax' | 'float') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'layeredMedia';
      }
    | {
        kicker?: string | null;
        text: string;
        mode?: ('center' | 'edge' | 'marquee') | null;
        accentWord?: string | null;
        align?: ('left' | 'center' | 'right') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'typographyTakeover';
      }
    | {
        video: number | Media;
        poster?: (number | null) | Media;
        title?: string | null;
        caption?: string | null;
        mode?: ('inline' | 'full' | 'sticky') | null;
        autoplay?: boolean | null;
        loop?: boolean | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'videoChapter';
      }
    | {
        title?: string | null;
        items?:
          | {
              title: string;
              value?: string | null;
              body?: string | null;
              id?: string | null;
            }[]
          | null;
        mode?: ('columns' | 'table' | 'cards') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'comparison';
      }
    | {
        items?:
          | {
              media: number | Media;
              label?: string | null;
              id?: string | null;
            }[]
          | null;
        mode?: ('fan' | 'stack' | 'spread') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'artifactStack';
      }
    | {
        eyebrow?: string | null;
        title: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        media: number | Media;
        layout?: ('text-left' | 'text-right' | 'balanced') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'textMedia';
      }
    | {
        title: string;
        body?: string | null;
        buttonLabel?: string | null;
        buttonURL?: string | null;
        media?: (number | null) | Media;
        mode?: ('minimal' | 'statement' | 'media') | null;
        theme?: ('dark' | 'light' | 'media') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        width?: ('full' | 'wide' | 'reading') | null;
        align?: ('left' | 'center' | 'right') | null;
        spacing?: ('none' | 'small' | 'medium' | 'large') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'editorialText';
      }
    | {
        media: number | Media;
        caption?: string | null;
        width?: ('full' | 'wide' | 'reading') | null;
        aspect?: ('auto' | 'landscape' | 'classic' | 'square' | 'portrait') | null;
        align?: ('left' | 'center' | 'right') | null;
        spacing?: ('none' | 'small' | 'medium' | 'large') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaFrame';
      }
    | {
        items: {
          media: number | Media;
          caption?: string | null;
          id?: string | null;
        }[];
        columns?: ('2' | '3' | '4') | null;
        gap?: number | null;
        width?: ('full' | 'wide' | 'reading') | null;
        aspect?: ('auto' | 'landscape' | 'classic' | 'square' | 'portrait') | null;
        spacing?: ('none' | 'small' | 'medium' | 'large') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaGrid';
      }
    | {
        items: {
          title?: string | null;
          body: string;
          id?: string | null;
        }[];
        width?: ('full' | 'wide' | 'reading') | null;
        spacing?: ('none' | 'small' | 'medium' | 'large') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'textColumns';
      }
    | {
        items: {
          label: string;
          value: string;
          id?: string | null;
        }[];
        width?: ('full' | 'wide' | 'reading') | null;
        spacing?: ('none' | 'small' | 'medium' | 'large') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'projectFacts';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        line?: boolean | null;
        height?: number | null;
        width?: ('full' | 'wide' | 'reading') | null;
        squareMedia?: boolean | null;
        flushTop?: boolean | null;
        flushBottom?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'sectionBreak';
      }
  )[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  submissionKey?: string | null;
  submissionHash?: string | null;
  name: string;
  email?: string | null;
  phone?: string | null;
  companyName?: string | null;
  company?: (number | null) | Company;
  message?: string | null;
  service?: ('presentation' | 'strategy' | 'branding' | 'web' | 'conference' | 'other') | null;
  budget?: number | null;
  status: 'new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost';
  source?: ('site' | 'referral' | 'outbound' | 'event' | 'other') | null;
  owner?: (number | null) | User;
  nextActionAt?: string | null;
  notes?: string | null;
  relatedProject?: (number | null) | Project;
  utm?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
    content?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  name: string;
  domain?: string | null;
  industry?: string | null;
  owner?: (number | null) | User;
  city?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals".
 */
export interface Deal {
  id: number;
  title: string;
  company: number | Company;
  lead?: (number | null) | Lead;
  stage: 'discovery' | 'brief' | 'estimate' | 'proposal' | 'negotiation' | 'won' | 'lost';
  probability?: number | null;
  value?: number | null;
  currency?: ('RUB' | 'USD' | 'EUR' | 'AED') | null;
  owner?: (number | null) | User;
  nextActionAt?: string | null;
  project?: (number | null) | Project;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  type: 'task' | 'call' | 'email' | 'meeting' | 'note';
  done?: boolean | null;
  title: string;
  body?: string | null;
  lead?: (number | null) | Lead;
  company?: (number | null) | Company;
  deal?: (number | null) | Deal;
  dueAt?: string | null;
  owner?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'case-templates';
        value: number | CaseTemplate;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'deals';
        value: number | Deal;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  lastEditedBy?: T;
  workflowStatus?: T;
  owner?: T;
  deadline?: T;
  title?: T;
  kind?: T;
  slug?: T;
  featured?: T;
  portfolioOrder?: T;
  role?: T;
  audience?: T;
  client?: T;
  year?: T;
  categories?:
    | T
    | {
        label?: T;
        id?: T;
      };
  summary?: T;
  cover?: T;
  ogImage?: T;
  pageBackground?: T;
  mediaRadius?: T;
  accent?: T;
  pageTheme?: T;
  bodyMode?: T;
  embedURL?: T;
  embedHeight?: T;
  embedMobileHeight?: T;
  embedAutoHeight?: T;
  blocks?:
    | T
    | {
        caseHero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              dek?: T;
              media?: T;
              layout?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        manifesto?:
          | T
          | {
              kicker?: T;
              text?: T;
              size?: T;
              align?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        fullBleedMedia?:
          | T
          | {
              media?: T;
              caption?: T;
              height?: T;
              fit?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        splitMedia?:
          | T
          | {
              left?: T;
              right?: T;
              ratio?: T;
              gap?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        mediaMosaic?:
          | T
          | {
              items?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    span?: T;
                    id?: T;
                  };
              layout?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        stickyStory?:
          | T
          | {
              chapter?: T;
              title?: T;
              body?: T;
              frames?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    id?: T;
                  };
              pin?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        metrics?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    note?: T;
                    id?: T;
                  };
              style?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        beforeAfter?:
          | T
          | {
              before?: T;
              after?: T;
              beforeLabel?: T;
              afterLabel?: T;
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              author?: T;
              role?: T;
              size?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        process?:
          | T
          | {
              title?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    media?: T;
                    id?: T;
                  };
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              items?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    id?: T;
                  };
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        deviceShowcase?:
          | T
          | {
              media?: T;
              device?: T;
              caption?: T;
              float?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        credits?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    role?: T;
                    name?: T;
                    id?: T;
                  };
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        nextProject?:
          | T
          | {
              project?: T;
              label?: T;
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        horizontalStory?:
          | T
          | {
              title?: T;
              scenes?:
                | T
                | {
                    media?: T;
                    title?: T;
                    caption?: T;
                    id?: T;
                  };
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        layeredMedia?:
          | T
          | {
              layers?:
                | T
                | {
                    media?: T;
                    x?: T;
                    y?: T;
                    width?: T;
                    depth?: T;
                    id?: T;
                  };
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        typographyTakeover?:
          | T
          | {
              kicker?: T;
              text?: T;
              mode?: T;
              accentWord?: T;
              align?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        videoChapter?:
          | T
          | {
              video?: T;
              poster?: T;
              title?: T;
              caption?: T;
              mode?: T;
              autoplay?: T;
              loop?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        comparison?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    title?: T;
                    value?: T;
                    body?: T;
                    id?: T;
                  };
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        artifactStack?:
          | T
          | {
              items?:
                | T
                | {
                    media?: T;
                    label?: T;
                    id?: T;
                  };
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        textMedia?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              media?: T;
              layout?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              body?: T;
              buttonLabel?: T;
              buttonURL?: T;
              media?: T;
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        editorialText?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              width?: T;
              align?: T;
              spacing?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        mediaFrame?:
          | T
          | {
              media?: T;
              caption?: T;
              width?: T;
              aspect?: T;
              align?: T;
              spacing?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        mediaGrid?:
          | T
          | {
              items?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    id?: T;
                  };
              columns?: T;
              gap?: T;
              width?: T;
              aspect?: T;
              spacing?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        textColumns?:
          | T
          | {
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              width?: T;
              spacing?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        projectFacts?:
          | T
          | {
              items?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              width?: T;
              spacing?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        sectionBreak?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              line?: T;
              height?: T;
              width?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
      };
  seoTitle?: T;
  seoDescription?: T;
  canonicalURL?: T;
  noIndex?: T;
  internalNotes?: T;
  sourceURL?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  lastEditedBy?: T;
  title?: T;
  slug?: T;
  author?: T;
  publishedAt?: T;
  summary?: T;
  cover?: T;
  categories?:
    | T
    | {
        label?: T;
        id?: T;
      };
  blocks?:
    | T
    | {
        articleText?:
          | T
          | {
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              title?: T;
              body?: T;
              width?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        fullBleedMedia?:
          | T
          | {
              media?: T;
              caption?: T;
              height?: T;
              fit?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        splitMedia?:
          | T
          | {
              left?: T;
              right?: T;
              ratio?: T;
              gap?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        mediaMosaic?:
          | T
          | {
              items?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    span?: T;
                    id?: T;
                  };
              layout?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        metrics?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    note?: T;
                    id?: T;
                  };
              style?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              author?: T;
              role?: T;
              size?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        process?:
          | T
          | {
              title?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    media?: T;
                    id?: T;
                  };
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              items?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    id?: T;
                  };
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        videoChapter?:
          | T
          | {
              video?: T;
              poster?: T;
              title?: T;
              caption?: T;
              mode?: T;
              autoplay?: T;
              loop?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        textMedia?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              media?: T;
              layout?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              body?: T;
              buttonLabel?: T;
              buttonURL?: T;
              media?: T;
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
      };
  pageTheme?: T;
  pageBackground?: T;
  mediaRadius?: T;
  featured?: T;
  workflowStatus?: T;
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  canonicalURL?: T;
  noIndex?: T;
  owner?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-templates_select".
 */
export interface CaseTemplatesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  pageTheme?: T;
  accent?: T;
  blocks?:
    | T
    | {
        caseHero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              dek?: T;
              media?: T;
              layout?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        manifesto?:
          | T
          | {
              kicker?: T;
              text?: T;
              size?: T;
              align?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        fullBleedMedia?:
          | T
          | {
              media?: T;
              caption?: T;
              height?: T;
              fit?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        splitMedia?:
          | T
          | {
              left?: T;
              right?: T;
              ratio?: T;
              gap?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        mediaMosaic?:
          | T
          | {
              items?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    span?: T;
                    id?: T;
                  };
              layout?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        stickyStory?:
          | T
          | {
              chapter?: T;
              title?: T;
              body?: T;
              frames?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    id?: T;
                  };
              pin?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        metrics?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    note?: T;
                    id?: T;
                  };
              style?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        beforeAfter?:
          | T
          | {
              before?: T;
              after?: T;
              beforeLabel?: T;
              afterLabel?: T;
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              author?: T;
              role?: T;
              size?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        process?:
          | T
          | {
              title?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    media?: T;
                    id?: T;
                  };
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              items?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    id?: T;
                  };
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        deviceShowcase?:
          | T
          | {
              media?: T;
              device?: T;
              caption?: T;
              float?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        credits?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    role?: T;
                    name?: T;
                    id?: T;
                  };
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        nextProject?:
          | T
          | {
              project?: T;
              label?: T;
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        horizontalStory?:
          | T
          | {
              title?: T;
              scenes?:
                | T
                | {
                    media?: T;
                    title?: T;
                    caption?: T;
                    id?: T;
                  };
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        layeredMedia?:
          | T
          | {
              layers?:
                | T
                | {
                    media?: T;
                    x?: T;
                    y?: T;
                    width?: T;
                    depth?: T;
                    id?: T;
                  };
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        typographyTakeover?:
          | T
          | {
              kicker?: T;
              text?: T;
              mode?: T;
              accentWord?: T;
              align?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        videoChapter?:
          | T
          | {
              video?: T;
              poster?: T;
              title?: T;
              caption?: T;
              mode?: T;
              autoplay?: T;
              loop?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        comparison?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    title?: T;
                    value?: T;
                    body?: T;
                    id?: T;
                  };
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        artifactStack?:
          | T
          | {
              items?:
                | T
                | {
                    media?: T;
                    label?: T;
                    id?: T;
                  };
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        textMedia?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              media?: T;
              layout?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              body?: T;
              buttonLabel?: T;
              buttonURL?: T;
              media?: T;
              mode?: T;
              theme?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        editorialText?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              width?: T;
              align?: T;
              spacing?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        mediaFrame?:
          | T
          | {
              media?: T;
              caption?: T;
              width?: T;
              aspect?: T;
              align?: T;
              spacing?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        mediaGrid?:
          | T
          | {
              items?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    id?: T;
                  };
              columns?: T;
              gap?: T;
              width?: T;
              aspect?: T;
              spacing?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        textColumns?:
          | T
          | {
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              width?: T;
              spacing?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        projectFacts?:
          | T
          | {
              items?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              width?: T;
              spacing?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
        sectionBreak?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              line?: T;
              height?: T;
              width?: T;
              squareMedia?: T;
              flushTop?: T;
              flushBottom?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  sourceProtected?: T;
  alt?: T;
  kind?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xl?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  submissionKey?: T;
  submissionHash?: T;
  name?: T;
  email?: T;
  phone?: T;
  companyName?: T;
  company?: T;
  message?: T;
  service?: T;
  budget?: T;
  status?: T;
  source?: T;
  owner?: T;
  nextActionAt?: T;
  notes?: T;
  relatedProject?: T;
  utm?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
        content?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  domain?: T;
  industry?: T;
  owner?: T;
  city?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals_select".
 */
export interface DealsSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  lead?: T;
  stage?: T;
  probability?: T;
  value?: T;
  currency?: T;
  owner?: T;
  nextActionAt?: T;
  project?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  type?: T;
  done?: T;
  title?: T;
  body?: T;
  lead?: T;
  company?: T;
  deal?: T;
  dueAt?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  publicContent?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  siteName?: string | null;
  siteURL?: string | null;
  defaultDescription?: string | null;
  defaultOG?: (number | null) | Media;
  email?: string | null;
  telegram?: string | null;
  phone?: string | null;
  /**
   * Опционально: n8n / Make / собственный endpoint. Секреты сюда не кладём.
   */
  leadWebhookURL?: string | null;
  analyticsId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  publicContent?: T;
  siteName?: T;
  siteURL?: T;
  defaultDescription?: T;
  defaultOG?: T;
  email?: T;
  telegram?: T;
  phone?: T;
  leadWebhookURL?: T;
  analyticsId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "overview_widget".
 */
export interface OverviewWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quick-actions_widget".
 */
export interface QuickActionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'small' | 'medium';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recent-projects_widget".
 */
export interface RecentProjectsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-queue_widget".
 */
export interface ReviewQueueWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pipeline_widget".
 */
export interface PipelineWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-inbox_widget".
 */
export interface LeadInboxWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_widget".
 */
export interface ActivitiesWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "block-library_widget".
 */
export interface BlockLibraryWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'projects';
      value: number | Project;
    } | null;
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}