import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "projects_blocks_editorial_text" ALTER COLUMN "spacing" SET DEFAULT 'small';
  ALTER TABLE "projects_blocks_media_frame" ALTER COLUMN "spacing" SET DEFAULT 'small';
  ALTER TABLE "projects_blocks_media_grid" ALTER COLUMN "spacing" SET DEFAULT 'small';
  ALTER TABLE "projects_blocks_text_columns" ALTER COLUMN "spacing" SET DEFAULT 'small';
  ALTER TABLE "projects_blocks_project_facts" ALTER COLUMN "spacing" SET DEFAULT 'small';
  ALTER TABLE "projects_blocks_section_break" ALTER COLUMN "height" SET DEFAULT 40;
  ALTER TABLE "_projects_v_blocks_editorial_text" ALTER COLUMN "spacing" SET DEFAULT 'small';
  ALTER TABLE "_projects_v_blocks_media_frame" ALTER COLUMN "spacing" SET DEFAULT 'small';
  ALTER TABLE "_projects_v_blocks_media_grid" ALTER COLUMN "spacing" SET DEFAULT 'small';
  ALTER TABLE "_projects_v_blocks_text_columns" ALTER COLUMN "spacing" SET DEFAULT 'small';
  ALTER TABLE "_projects_v_blocks_project_facts" ALTER COLUMN "spacing" SET DEFAULT 'small';
  ALTER TABLE "_projects_v_blocks_section_break" ALTER COLUMN "height" SET DEFAULT 40;
  ALTER TABLE "case_templates_blocks_editorial_text" ALTER COLUMN "spacing" SET DEFAULT 'small';
  ALTER TABLE "case_templates_blocks_media_frame" ALTER COLUMN "spacing" SET DEFAULT 'small';
  ALTER TABLE "case_templates_blocks_media_grid" ALTER COLUMN "spacing" SET DEFAULT 'small';
  ALTER TABLE "case_templates_blocks_text_columns" ALTER COLUMN "spacing" SET DEFAULT 'small';
  ALTER TABLE "case_templates_blocks_project_facts" ALTER COLUMN "spacing" SET DEFAULT 'small';
  ALTER TABLE "case_templates_blocks_section_break" ALTER COLUMN "height" SET DEFAULT 40;
  ALTER TABLE "_case_templates_v_blocks_editorial_text" ALTER COLUMN "spacing" SET DEFAULT 'small';
  ALTER TABLE "_case_templates_v_blocks_media_frame" ALTER COLUMN "spacing" SET DEFAULT 'small';
  ALTER TABLE "_case_templates_v_blocks_media_grid" ALTER COLUMN "spacing" SET DEFAULT 'small';
  ALTER TABLE "_case_templates_v_blocks_text_columns" ALTER COLUMN "spacing" SET DEFAULT 'small';
  ALTER TABLE "_case_templates_v_blocks_project_facts" ALTER COLUMN "spacing" SET DEFAULT 'small';
  ALTER TABLE "_case_templates_v_blocks_section_break" ALTER COLUMN "height" SET DEFAULT 40;
  ALTER TABLE "projects_blocks_case_hero" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_case_hero" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_case_hero" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_manifesto" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_manifesto" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_manifesto" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_full_bleed_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_full_bleed_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_full_bleed_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_split_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_split_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_split_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_media_mosaic" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_media_mosaic" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_media_mosaic" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_sticky_story" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_sticky_story" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_sticky_story" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_metrics" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_metrics" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_metrics" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_before_after" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_before_after" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_before_after" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_quote" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_quote" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_quote" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_process" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_process" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_process" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_gallery" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_gallery" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_gallery" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_device_showcase" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_device_showcase" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_device_showcase" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_credits" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_credits" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_credits" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_next_project" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_next_project" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_next_project" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_horizontal_story" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_horizontal_story" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_horizontal_story" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_layered_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_layered_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_layered_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_typography_takeover" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_typography_takeover" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_typography_takeover" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_video_chapter" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_video_chapter" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_video_chapter" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_comparison" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_comparison" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_comparison" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_artifact_stack" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_artifact_stack" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_artifact_stack" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_text_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_text_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_text_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_cta" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_cta" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_cta" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_editorial_text" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_editorial_text" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_editorial_text" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_media_frame" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_media_frame" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_media_frame" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_media_grid" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_media_grid" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_media_grid" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_text_columns" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_text_columns" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_text_columns" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_project_facts" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_project_facts" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_project_facts" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_section_break" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_section_break" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "projects_blocks_section_break" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_case_hero" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_case_hero" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_case_hero" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_manifesto" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_manifesto" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_manifesto" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_full_bleed_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_full_bleed_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_full_bleed_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_split_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_split_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_split_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_media_mosaic" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_media_mosaic" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_media_mosaic" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_sticky_story" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_sticky_story" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_sticky_story" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_metrics" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_metrics" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_metrics" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_before_after" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_before_after" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_before_after" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_quote" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_quote" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_quote" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_process" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_process" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_process" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_gallery" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_gallery" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_gallery" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_device_showcase" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_device_showcase" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_device_showcase" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_credits" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_credits" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_credits" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_next_project" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_next_project" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_next_project" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_horizontal_story" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_horizontal_story" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_horizontal_story" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_layered_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_layered_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_layered_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_typography_takeover" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_typography_takeover" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_typography_takeover" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_video_chapter" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_video_chapter" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_video_chapter" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_comparison" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_comparison" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_comparison" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_artifact_stack" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_artifact_stack" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_artifact_stack" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_text_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_text_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_text_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_cta" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_cta" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_cta" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_editorial_text" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_editorial_text" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_editorial_text" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_media_frame" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_media_frame" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_media_frame" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_media_grid" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_media_grid" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_media_grid" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_text_columns" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_text_columns" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_text_columns" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_project_facts" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_project_facts" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_project_facts" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_section_break" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_section_break" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_projects_v_blocks_section_break" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_article_text" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_article_text" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_article_text" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_full_bleed_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_full_bleed_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_full_bleed_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_split_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_split_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_split_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_media_mosaic" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_media_mosaic" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_media_mosaic" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_metrics" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_metrics" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_metrics" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_quote" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_quote" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_quote" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_process" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_process" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_process" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_gallery" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_gallery" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_gallery" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_video_chapter" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_video_chapter" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_video_chapter" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_text_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_text_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_text_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_cta" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_cta" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "articles_blocks_cta" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_article_text" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_article_text" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_article_text" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_full_bleed_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_full_bleed_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_full_bleed_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_split_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_split_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_split_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_media_mosaic" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_media_mosaic" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_media_mosaic" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_metrics" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_metrics" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_metrics" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_quote" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_quote" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_quote" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_process" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_process" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_process" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_gallery" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_gallery" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_gallery" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_video_chapter" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_video_chapter" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_video_chapter" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_text_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_text_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_text_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_cta" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_cta" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_articles_v_blocks_cta" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_case_hero" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_case_hero" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_case_hero" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_manifesto" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_manifesto" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_manifesto" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_full_bleed_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_full_bleed_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_full_bleed_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_split_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_split_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_split_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_media_mosaic" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_media_mosaic" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_media_mosaic" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_sticky_story" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_sticky_story" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_sticky_story" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_metrics" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_metrics" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_metrics" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_before_after" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_before_after" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_before_after" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_quote" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_quote" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_quote" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_process" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_process" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_process" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_gallery" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_gallery" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_gallery" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_device_showcase" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_device_showcase" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_device_showcase" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_credits" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_credits" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_credits" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_next_project" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_next_project" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_next_project" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_horizontal_story" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_horizontal_story" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_horizontal_story" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_layered_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_layered_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_layered_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_typography_takeover" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_typography_takeover" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_typography_takeover" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_video_chapter" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_video_chapter" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_video_chapter" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_comparison" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_comparison" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_comparison" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_artifact_stack" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_artifact_stack" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_artifact_stack" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_text_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_text_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_text_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_cta" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_cta" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_cta" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_editorial_text" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_editorial_text" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_editorial_text" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_media_frame" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_media_frame" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_media_frame" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_media_grid" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_media_grid" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_media_grid" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_text_columns" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_text_columns" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_text_columns" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_project_facts" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_project_facts" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_project_facts" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_section_break" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_section_break" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "case_templates_blocks_section_break" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_case_hero" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_case_hero" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_case_hero" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_manifesto" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_manifesto" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_manifesto" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_full_bleed_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_full_bleed_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_full_bleed_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_split_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_split_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_split_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_media_mosaic" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_media_mosaic" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_media_mosaic" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_sticky_story" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_sticky_story" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_sticky_story" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_metrics" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_metrics" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_metrics" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_before_after" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_before_after" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_before_after" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_quote" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_quote" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_quote" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_process" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_process" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_process" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_gallery" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_gallery" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_gallery" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_device_showcase" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_device_showcase" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_device_showcase" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_credits" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_credits" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_credits" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_next_project" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_next_project" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_next_project" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_horizontal_story" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_horizontal_story" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_horizontal_story" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_layered_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_layered_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_layered_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_typography_takeover" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_typography_takeover" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_typography_takeover" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_video_chapter" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_video_chapter" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_video_chapter" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_comparison" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_comparison" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_comparison" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_artifact_stack" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_artifact_stack" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_artifact_stack" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_text_media" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_text_media" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_text_media" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_cta" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_cta" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_cta" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_editorial_text" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_editorial_text" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_editorial_text" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_media_frame" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_media_frame" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_media_frame" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_media_grid" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_media_grid" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_media_grid" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_text_columns" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_text_columns" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_text_columns" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_project_facts" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_project_facts" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_project_facts" ADD COLUMN "flush_bottom" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_section_break" ADD COLUMN "square_media" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_section_break" ADD COLUMN "flush_top" boolean DEFAULT false;
  ALTER TABLE "_case_templates_v_blocks_section_break" ADD COLUMN "flush_bottom" boolean DEFAULT false;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "projects_blocks_editorial_text" ALTER COLUMN "spacing" SET DEFAULT 'medium';
  ALTER TABLE "projects_blocks_media_frame" ALTER COLUMN "spacing" SET DEFAULT 'medium';
  ALTER TABLE "projects_blocks_media_grid" ALTER COLUMN "spacing" SET DEFAULT 'medium';
  ALTER TABLE "projects_blocks_text_columns" ALTER COLUMN "spacing" SET DEFAULT 'medium';
  ALTER TABLE "projects_blocks_project_facts" ALTER COLUMN "spacing" SET DEFAULT 'medium';
  ALTER TABLE "projects_blocks_section_break" ALTER COLUMN "height" SET DEFAULT 80;
  ALTER TABLE "_projects_v_blocks_editorial_text" ALTER COLUMN "spacing" SET DEFAULT 'medium';
  ALTER TABLE "_projects_v_blocks_media_frame" ALTER COLUMN "spacing" SET DEFAULT 'medium';
  ALTER TABLE "_projects_v_blocks_media_grid" ALTER COLUMN "spacing" SET DEFAULT 'medium';
  ALTER TABLE "_projects_v_blocks_text_columns" ALTER COLUMN "spacing" SET DEFAULT 'medium';
  ALTER TABLE "_projects_v_blocks_project_facts" ALTER COLUMN "spacing" SET DEFAULT 'medium';
  ALTER TABLE "_projects_v_blocks_section_break" ALTER COLUMN "height" SET DEFAULT 80;
  ALTER TABLE "case_templates_blocks_editorial_text" ALTER COLUMN "spacing" SET DEFAULT 'medium';
  ALTER TABLE "case_templates_blocks_media_frame" ALTER COLUMN "spacing" SET DEFAULT 'medium';
  ALTER TABLE "case_templates_blocks_media_grid" ALTER COLUMN "spacing" SET DEFAULT 'medium';
  ALTER TABLE "case_templates_blocks_text_columns" ALTER COLUMN "spacing" SET DEFAULT 'medium';
  ALTER TABLE "case_templates_blocks_project_facts" ALTER COLUMN "spacing" SET DEFAULT 'medium';
  ALTER TABLE "case_templates_blocks_section_break" ALTER COLUMN "height" SET DEFAULT 80;
  ALTER TABLE "_case_templates_v_blocks_editorial_text" ALTER COLUMN "spacing" SET DEFAULT 'medium';
  ALTER TABLE "_case_templates_v_blocks_media_frame" ALTER COLUMN "spacing" SET DEFAULT 'medium';
  ALTER TABLE "_case_templates_v_blocks_media_grid" ALTER COLUMN "spacing" SET DEFAULT 'medium';
  ALTER TABLE "_case_templates_v_blocks_text_columns" ALTER COLUMN "spacing" SET DEFAULT 'medium';
  ALTER TABLE "_case_templates_v_blocks_project_facts" ALTER COLUMN "spacing" SET DEFAULT 'medium';
  ALTER TABLE "_case_templates_v_blocks_section_break" ALTER COLUMN "height" SET DEFAULT 80;
  ALTER TABLE "projects_blocks_case_hero" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_case_hero" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_case_hero" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_manifesto" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_manifesto" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_manifesto" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_full_bleed_media" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_full_bleed_media" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_full_bleed_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_split_media" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_split_media" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_split_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_media_mosaic" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_media_mosaic" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_media_mosaic" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_sticky_story" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_sticky_story" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_sticky_story" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_metrics" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_metrics" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_metrics" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_before_after" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_before_after" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_before_after" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_quote" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_quote" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_quote" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_process" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_process" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_process" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_gallery" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_gallery" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_gallery" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_device_showcase" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_device_showcase" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_device_showcase" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_credits" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_credits" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_credits" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_next_project" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_next_project" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_next_project" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_horizontal_story" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_horizontal_story" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_horizontal_story" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_layered_media" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_layered_media" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_layered_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_typography_takeover" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_typography_takeover" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_typography_takeover" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_video_chapter" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_video_chapter" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_video_chapter" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_comparison" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_comparison" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_comparison" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_artifact_stack" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_artifact_stack" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_artifact_stack" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_text_media" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_text_media" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_text_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_cta" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_cta" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_cta" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_editorial_text" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_editorial_text" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_editorial_text" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_media_frame" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_media_frame" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_media_frame" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_media_grid" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_media_grid" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_media_grid" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_text_columns" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_text_columns" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_text_columns" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_project_facts" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_project_facts" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_project_facts" DROP COLUMN "flush_bottom";
  ALTER TABLE "projects_blocks_section_break" DROP COLUMN "square_media";
  ALTER TABLE "projects_blocks_section_break" DROP COLUMN "flush_top";
  ALTER TABLE "projects_blocks_section_break" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_case_hero" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_case_hero" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_case_hero" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_manifesto" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_manifesto" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_manifesto" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_full_bleed_media" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_full_bleed_media" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_full_bleed_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_split_media" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_split_media" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_split_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_media_mosaic" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_media_mosaic" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_media_mosaic" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_sticky_story" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_sticky_story" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_sticky_story" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_metrics" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_metrics" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_metrics" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_before_after" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_before_after" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_before_after" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_quote" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_quote" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_quote" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_process" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_process" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_process" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_gallery" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_gallery" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_gallery" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_device_showcase" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_device_showcase" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_device_showcase" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_credits" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_credits" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_credits" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_next_project" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_next_project" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_next_project" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_horizontal_story" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_horizontal_story" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_horizontal_story" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_layered_media" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_layered_media" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_layered_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_typography_takeover" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_typography_takeover" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_typography_takeover" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_video_chapter" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_video_chapter" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_video_chapter" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_comparison" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_comparison" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_comparison" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_artifact_stack" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_artifact_stack" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_artifact_stack" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_text_media" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_text_media" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_text_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_cta" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_cta" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_cta" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_editorial_text" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_editorial_text" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_editorial_text" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_media_frame" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_media_frame" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_media_frame" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_media_grid" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_media_grid" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_media_grid" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_text_columns" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_text_columns" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_text_columns" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_project_facts" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_project_facts" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_project_facts" DROP COLUMN "flush_bottom";
  ALTER TABLE "_projects_v_blocks_section_break" DROP COLUMN "square_media";
  ALTER TABLE "_projects_v_blocks_section_break" DROP COLUMN "flush_top";
  ALTER TABLE "_projects_v_blocks_section_break" DROP COLUMN "flush_bottom";
  ALTER TABLE "articles_blocks_article_text" DROP COLUMN "square_media";
  ALTER TABLE "articles_blocks_article_text" DROP COLUMN "flush_top";
  ALTER TABLE "articles_blocks_article_text" DROP COLUMN "flush_bottom";
  ALTER TABLE "articles_blocks_full_bleed_media" DROP COLUMN "square_media";
  ALTER TABLE "articles_blocks_full_bleed_media" DROP COLUMN "flush_top";
  ALTER TABLE "articles_blocks_full_bleed_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "articles_blocks_split_media" DROP COLUMN "square_media";
  ALTER TABLE "articles_blocks_split_media" DROP COLUMN "flush_top";
  ALTER TABLE "articles_blocks_split_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "articles_blocks_media_mosaic" DROP COLUMN "square_media";
  ALTER TABLE "articles_blocks_media_mosaic" DROP COLUMN "flush_top";
  ALTER TABLE "articles_blocks_media_mosaic" DROP COLUMN "flush_bottom";
  ALTER TABLE "articles_blocks_metrics" DROP COLUMN "square_media";
  ALTER TABLE "articles_blocks_metrics" DROP COLUMN "flush_top";
  ALTER TABLE "articles_blocks_metrics" DROP COLUMN "flush_bottom";
  ALTER TABLE "articles_blocks_quote" DROP COLUMN "square_media";
  ALTER TABLE "articles_blocks_quote" DROP COLUMN "flush_top";
  ALTER TABLE "articles_blocks_quote" DROP COLUMN "flush_bottom";
  ALTER TABLE "articles_blocks_process" DROP COLUMN "square_media";
  ALTER TABLE "articles_blocks_process" DROP COLUMN "flush_top";
  ALTER TABLE "articles_blocks_process" DROP COLUMN "flush_bottom";
  ALTER TABLE "articles_blocks_gallery" DROP COLUMN "square_media";
  ALTER TABLE "articles_blocks_gallery" DROP COLUMN "flush_top";
  ALTER TABLE "articles_blocks_gallery" DROP COLUMN "flush_bottom";
  ALTER TABLE "articles_blocks_video_chapter" DROP COLUMN "square_media";
  ALTER TABLE "articles_blocks_video_chapter" DROP COLUMN "flush_top";
  ALTER TABLE "articles_blocks_video_chapter" DROP COLUMN "flush_bottom";
  ALTER TABLE "articles_blocks_text_media" DROP COLUMN "square_media";
  ALTER TABLE "articles_blocks_text_media" DROP COLUMN "flush_top";
  ALTER TABLE "articles_blocks_text_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "articles_blocks_cta" DROP COLUMN "square_media";
  ALTER TABLE "articles_blocks_cta" DROP COLUMN "flush_top";
  ALTER TABLE "articles_blocks_cta" DROP COLUMN "flush_bottom";
  ALTER TABLE "_articles_v_blocks_article_text" DROP COLUMN "square_media";
  ALTER TABLE "_articles_v_blocks_article_text" DROP COLUMN "flush_top";
  ALTER TABLE "_articles_v_blocks_article_text" DROP COLUMN "flush_bottom";
  ALTER TABLE "_articles_v_blocks_full_bleed_media" DROP COLUMN "square_media";
  ALTER TABLE "_articles_v_blocks_full_bleed_media" DROP COLUMN "flush_top";
  ALTER TABLE "_articles_v_blocks_full_bleed_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "_articles_v_blocks_split_media" DROP COLUMN "square_media";
  ALTER TABLE "_articles_v_blocks_split_media" DROP COLUMN "flush_top";
  ALTER TABLE "_articles_v_blocks_split_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "_articles_v_blocks_media_mosaic" DROP COLUMN "square_media";
  ALTER TABLE "_articles_v_blocks_media_mosaic" DROP COLUMN "flush_top";
  ALTER TABLE "_articles_v_blocks_media_mosaic" DROP COLUMN "flush_bottom";
  ALTER TABLE "_articles_v_blocks_metrics" DROP COLUMN "square_media";
  ALTER TABLE "_articles_v_blocks_metrics" DROP COLUMN "flush_top";
  ALTER TABLE "_articles_v_blocks_metrics" DROP COLUMN "flush_bottom";
  ALTER TABLE "_articles_v_blocks_quote" DROP COLUMN "square_media";
  ALTER TABLE "_articles_v_blocks_quote" DROP COLUMN "flush_top";
  ALTER TABLE "_articles_v_blocks_quote" DROP COLUMN "flush_bottom";
  ALTER TABLE "_articles_v_blocks_process" DROP COLUMN "square_media";
  ALTER TABLE "_articles_v_blocks_process" DROP COLUMN "flush_top";
  ALTER TABLE "_articles_v_blocks_process" DROP COLUMN "flush_bottom";
  ALTER TABLE "_articles_v_blocks_gallery" DROP COLUMN "square_media";
  ALTER TABLE "_articles_v_blocks_gallery" DROP COLUMN "flush_top";
  ALTER TABLE "_articles_v_blocks_gallery" DROP COLUMN "flush_bottom";
  ALTER TABLE "_articles_v_blocks_video_chapter" DROP COLUMN "square_media";
  ALTER TABLE "_articles_v_blocks_video_chapter" DROP COLUMN "flush_top";
  ALTER TABLE "_articles_v_blocks_video_chapter" DROP COLUMN "flush_bottom";
  ALTER TABLE "_articles_v_blocks_text_media" DROP COLUMN "square_media";
  ALTER TABLE "_articles_v_blocks_text_media" DROP COLUMN "flush_top";
  ALTER TABLE "_articles_v_blocks_text_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "_articles_v_blocks_cta" DROP COLUMN "square_media";
  ALTER TABLE "_articles_v_blocks_cta" DROP COLUMN "flush_top";
  ALTER TABLE "_articles_v_blocks_cta" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_case_hero" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_case_hero" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_case_hero" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_manifesto" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_manifesto" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_manifesto" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_full_bleed_media" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_full_bleed_media" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_full_bleed_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_split_media" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_split_media" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_split_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_media_mosaic" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_media_mosaic" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_media_mosaic" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_sticky_story" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_sticky_story" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_sticky_story" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_metrics" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_metrics" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_metrics" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_before_after" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_before_after" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_before_after" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_quote" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_quote" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_quote" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_process" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_process" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_process" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_gallery" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_gallery" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_gallery" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_device_showcase" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_device_showcase" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_device_showcase" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_credits" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_credits" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_credits" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_next_project" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_next_project" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_next_project" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_horizontal_story" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_horizontal_story" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_horizontal_story" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_layered_media" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_layered_media" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_layered_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_typography_takeover" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_typography_takeover" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_typography_takeover" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_video_chapter" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_video_chapter" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_video_chapter" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_comparison" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_comparison" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_comparison" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_artifact_stack" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_artifact_stack" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_artifact_stack" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_text_media" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_text_media" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_text_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_cta" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_cta" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_cta" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_editorial_text" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_editorial_text" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_editorial_text" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_media_frame" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_media_frame" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_media_frame" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_media_grid" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_media_grid" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_media_grid" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_text_columns" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_text_columns" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_text_columns" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_project_facts" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_project_facts" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_project_facts" DROP COLUMN "flush_bottom";
  ALTER TABLE "case_templates_blocks_section_break" DROP COLUMN "square_media";
  ALTER TABLE "case_templates_blocks_section_break" DROP COLUMN "flush_top";
  ALTER TABLE "case_templates_blocks_section_break" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_case_hero" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_case_hero" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_case_hero" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_manifesto" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_manifesto" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_manifesto" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_full_bleed_media" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_full_bleed_media" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_full_bleed_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_split_media" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_split_media" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_split_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_media_mosaic" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_media_mosaic" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_media_mosaic" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_sticky_story" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_sticky_story" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_sticky_story" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_metrics" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_metrics" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_metrics" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_before_after" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_before_after" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_before_after" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_quote" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_quote" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_quote" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_process" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_process" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_process" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_gallery" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_gallery" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_gallery" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_device_showcase" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_device_showcase" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_device_showcase" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_credits" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_credits" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_credits" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_next_project" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_next_project" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_next_project" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_horizontal_story" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_horizontal_story" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_horizontal_story" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_layered_media" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_layered_media" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_layered_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_typography_takeover" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_typography_takeover" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_typography_takeover" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_video_chapter" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_video_chapter" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_video_chapter" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_comparison" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_comparison" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_comparison" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_artifact_stack" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_artifact_stack" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_artifact_stack" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_text_media" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_text_media" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_text_media" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_cta" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_cta" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_cta" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_editorial_text" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_editorial_text" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_editorial_text" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_media_frame" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_media_frame" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_media_frame" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_media_grid" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_media_grid" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_media_grid" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_text_columns" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_text_columns" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_text_columns" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_project_facts" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_project_facts" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_project_facts" DROP COLUMN "flush_bottom";
  ALTER TABLE "_case_templates_v_blocks_section_break" DROP COLUMN "square_media";
  ALTER TABLE "_case_templates_v_blocks_section_break" DROP COLUMN "flush_top";
  ALTER TABLE "_case_templates_v_blocks_section_break" DROP COLUMN "flush_bottom";`)
}
