'use client'
import {useRef,useState,type FormEvent} from 'react'
import {track} from './telemetry'
export default function ContactForm({project:initialProject='',email,comparison=false}:{project?:string;email:string;comparison?:boolean}){
 const [project,setProject]=useState(initialProject),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[sent,setSent]=useState(false),[failed,setFailed]=useState(false),key=useRef(''),started=useRef(false)
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy||sent)return;const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));if(!key.current)key.current=crypto.randomUUID();setBusy(true);setStatus('');setFailed(false);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000)
 try{const response=await fetch('/api/leads/submit',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key.current},body:JSON.stringify({...values,project,submissionKey:key.current}),signal:controller.signal});if(!response.ok)throw Error('submit_failed');setSent(true);setStatus(comparison?'Заявка сохранена в тестовой CRM новой версии. Команда не получает уведомлений.':'Спасибо. Ваша задача отправлена команде BAEV.');track('contact_submit_success')}
 catch{setFailed(true);setStatus('Не удалось подтвердить отправку. Текст сохранён в форме. Попробуйте ещё раз или напишите нам на почту.');track('contact_submit_error')}finally{clearTimeout(timer);setBusy(false)}}
 return <form className="contact-form" onSubmit={submit} onChange={()=>{if(failed)key.current=''}} onFocus={()=>{if(!started.current){started.current=true;track('contact_start')}}}>{comparison&&<p className="form-note">Версия для сравнения: форма работает с отдельной тестовой CRM.</p>}{project&&<div className="contact-context"><span>По мотивам проекта: {project}</span><button type="button" onClick={()=>setProject('')} aria-label="Убрать проект из обращения">×</button></div>}<label>Ваше имя *<input name="name" autoComplete="name" required maxLength={160} placeholder="Как к вам обращаться" disabled={sent}/></label><label>Email *<input name="email" type="email" autoComplete="email" required maxLength={320} placeholder="you@company.com" disabled={sent}/></label><label>Задача *<textarea name="message" required rows={4} maxLength={4000} placeholder="Что нужно создать, для кого и к какому сроку?" disabled={sent}/></label><div className="honeypot" aria-hidden="true"><label>Сайт<input name="website" tabIndex={-1} autoComplete="off"/></label></div><p className="form-note">Поля со * обязательны. Имя, email и описание нужны команде BAEV, чтобы ответить на ваше обращение. Не отправляйте конфиденциальные материалы через форму.</p><button className="public-button" disabled={busy||sent}>{busy?'Отправляем…':sent?'Отправлено ✓':failed?'Повторить отправку ↗':'Отправить задачу ↗'}</button>{status&&<div className="form-status" role={failed?'alert':'status'}>{status}{failed&&<><br/><a href={'mailto:'+email}>{email}</a></>}</div>}</form>
}
